spring.application.name=ms-cuentas
server.port=8002

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/db_cuentas
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
